/* ULTRA@503 Phase 1 client. All authorization is enforced by Supabase RLS too. */
(() => {
  const cfg=window.APP_CONFIG||{};
  const ready=cfg.SUPABASE_URL?.startsWith("https://")&&!cfg.SUPABASE_URL.includes("YOUR-")&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes("YOUR_");
  const $=id=>document.getElementById(id);
  let sb,user,profile,stages=[],activeRoute=null,stream=null,scanTarget=null;
  const ROLE_STAGE={fitting:["fitting"],marking:["marking"],mpi_pmi:["mpi_pmi"],final_inspection:["final_inspection"],cmm:["cmm"],coating:["coating"],visual_inspection:["visual_inspection"],packing:["packing"],dispatch:["rfd","customer_pickup"],dock_audit:["dock_audit"]};
  const REWORK_ROLES=["admin","final_inspection","visual_inspection","packing","dock_audit"];
  const REJECT_ROLES=["admin","mpi_pmi","final_inspection","visual_inspection","dock_audit"];
  function toast(s){$("toast").textContent=s;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",4000)}
  function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
  function show(id,on=true){$(id).hidden=!on}
  function card(r,extra=""){return `<article class="record ${r.is_urgent?"urgent":""}"><h3>${esc(r.part_number||"Part")} — ${esc(r.po_number||"PO")}</h3><div><b>Route Card:</b> ${esc(r.route_card_no)} · <b>UC:</b> ${esc(r.uc_batch)} · <b>Heat:</b> ${esc(r.heat_batch||"—")}</div><div><b>Qty:</b> ${r.qty} · <b>Status:</b> ${esc(r.status)} · <b>Stage:</b> ${esc(r.stage_name||"—")}</div>${extra}<div class="record-actions"><button onclick="window.openRoute('${r.id}')">Open Route Card</button></div></article>`}
  async function init(){if(!ready){show("authPanel");$("authPanel").insertAdjacentHTML("beforeend",'<p style="color:#a22"><b>Setup required:</b> edit config.js with your Supabase URL and anon/publishable key.</p>');return}
    sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
    $("authForm").addEventListener("submit",login);$("profileForm").addEventListener("submit",saveProfile);$("signOutBtn").onclick=()=>sb.auth.signOut();
    $("searchBtn").onclick=search;$("scanSearchBtn").onclick=()=>startScan("search");$("scanNewBtn").onclick=()=>startScan("new");$("stopScan").onclick=stopScan;
    $("routeForm").addEventListener("submit",createRoute);
    $("tabs").addEventListener("click",e=>{let b=e.target.closest("button[data-tab]");if(b)tab(b.dataset.tab)});
    const {data:{session}}=await sb.auth.getSession();sb.auth.onAuthStateChange(()=>loadSession());if(session)await loadSession();
  }
  async function login(e){e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error)toast(error.message);else await loadSession()}
  async function loadSession(){const {data:{user:u}}=await sb.auth.getUser();user=u;if(!user){["profilePanel","pendingPanel","appPanel"].forEach(x=>show(x,false));show("authPanel");show("signOutBtn",false);return}
    show("authPanel",false);show("signOutBtn");let {data:p,error}=await sb.from("profiles").select("*").eq("id",user.id).maybeSingle();if(error){toast(error.message);return}
    profile=p;if(!p){show("profilePanel");show("pendingPanel",false);show("appPanel",false);return}
    if(!p.role){show("profilePanel",false);show("pendingPanel");show("appPanel",false);return}
    show("profilePanel",false);show("pendingPanel",false);show("appPanel");$("whoami").textContent=p.full_name+" · "+p.employee_id;$("roleBadge").textContent=p.role;
    show("newTab",["admin","fitting"].includes(p.role));show("urgentTab",["admin","supervisor"].includes(p.role));await loadStages();await dashboard();await poDashboard();if(["admin","supervisor"].includes(p.role))await urgent();
  }
  async function saveProfile(e){e.preventDefault();const {error}=await sb.from("profiles").upsert({id:user.id,full_name:$("fullName").value.trim(),employee_id:$("employeeId").value.trim()});if(error)toast(error.message);else{toast("Profile saved. Await role assignment.");await loadSession()}}
  async function loadStages(){let {data,error}=await sb.from("process_stages").select("*").order("sequence_order");if(error)toast(error.message);else stages=data||[]}
  function tab(name){document.querySelectorAll(".view").forEach(x=>x.hidden=true);show("routeDetail",false);show("view-"+name);document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===name))}
  async function enrich(rows){if(!rows?.length)return[];let ids=[...new Set(rows.map(x=>x.po_id))];let {data:pos}=await sb.from("pos").select("id,po_number,po_line,part_id,parts(part_number,description)").in("id",ids);let map=Object.fromEntries((pos||[]).map(p=>[p.id,p]));let sm=Object.fromEntries(stages.map(s=>[s.id,s.name]));return rows.map(r=>({...r,po_number:map[r.po_id]?.po_number,po_line:map[r.po_id]?.po_line,part_number:map[r.po_id]?.parts?.part_number,stage_name:sm[r.current_stage_id]}))}
  async function dashboard(){let {data,error}=await sb.from("route_cards").select("*").eq("is_deleted",false).order("created_at",{ascending:false}).limit(20);if(error){toast(error.message);return}let rows=await enrich(data||[]);$("searchResults").innerHTML=rows.map(r=>card(r)).join("")||"<p>No route cards yet.</p>";
    let {data:h}=await sb.from("handovers").select("*,route_cards(*)").eq("status","awaiting_receipt");let mine=(h||[]).filter(x=>stages.find(s=>s.id===x.to_stage_id)?.code===profile.role&&x.released_by!==user.id||profile.role==="admin");$("myReceipts").innerHTML=mine.map(x=>`<article class="record pulse"><b>${esc(x.route_cards?.route_card_no)}</b> · Qty ${x.quantity}<p>Awaiting receipt</p><button onclick="window.receiveHandover('${x.id}')">Receive</button></article>`).join("")||"<p>No handovers awaiting your receipt.</p>"}
  async function search(){let q=$("searchInput").value.trim();if(!q)return;let {data:parts}=await sb.from("parts").select("id").ilike("part_number",`%${q}%`);let {data:pos}=await sb.from("pos").select("id").or(`po_number.ilike.%${q}%`);let {data,error}=await sb.from("route_cards").select("*").eq("is_deleted",false).or(`route_card_no.ilike.%${q}%,uc_batch.ilike.%${q}%,heat_batch.ilike.%${q}%`).limit(50);let rows=data||[];let poids=(pos||[]).map(p=>p.id);if(poids.length){let x=await sb.from("route_cards").select("*").eq("is_deleted",false).in("po_id",poids);rows=rows.concat(x.data||[])}if(parts?.length){let pp=await sb.from("pos").select("id").in("part_id",parts.map(p=>p.id));let x=await sb.from("route_cards").select("*").eq("is_deleted",false).in("po_id",(pp.data||[]).map(p=>p.id));rows=rows.concat(x.data||[])}if(error)toast(error.message);let unique=[...new Map(rows.map(r=>[r.id,r])).values()];$("searchResults").innerHTML=(await enrich(unique)).map(r=>card(r)).join("")||"<p>No matches.</p>"}
  async function createRoute(e){e.preventDefault();let btn=$("createRouteBtn");btn.disabled=true;try{
    const partNo=$("partNumber").value.trim(),poNo=$("poNumber").value.trim(),line=$("poLine").value.trim(),uc=$("ucBatch").value.trim();
    let found=await sb.from("route_cards").select("id").eq("uc_batch",uc).eq("is_deleted",false);if(found.error)throw found.error;if(found.data?.length){toast("UC Batch already exists. Opening existing Route Card.");openRoute(found.data[0].id);return}
    let p=await sb.from("parts").select("id").eq("part_number",partNo);if(p.error)throw p.error;if(p.data.length>1)throw Error("Duplicate Part Number records; ask admin to clean data.");
    let partId=p.data[0]?.id;if(!partId){let ins=await sb.from("parts").insert({part_number:partNo,description:$("partDescription").value.trim()||null}).select("id").single();if(ins.error)throw ins.error;partId=ins.data.id}
    let po=await sb.from("pos").select("id").eq("po_number",poNo).eq("po_line",line);if(po.error)throw po.error;if(po.data.length>1)throw Error("Duplicate PO + line records; ask admin to clean data.");
    let poId=po.data[0]?.id;if(!poId){let ins=await sb.from("pos").insert({po_number:poNo,po_line:line,part_id:partId,customer_name:$("customerName").value.trim()||null,po_qty:Number($("poQty").value)||null}).select("id").single();if(ins.error)throw ins.error;poId=ins.data.id}
    let rc=$("routeCardNo").value.trim()||suggestRC(uc);let ins=await sb.from("route_cards").insert({route_card_no:rc,po_id:poId,uc_batch:uc,heat_batch:$("heatBatch").value.trim()||null,qty:Number($("routeQty").value),status:"active",current_stage_id:stages.find(s=>s.code==="fitting")?.id,qr_payload:$("qrPayload").value||null}).select("id").single();if(ins.error)throw ins.error;toast("Route Card created.");openRoute(ins.data.id)
  }catch(err){toast(err.message||String(err))}finally{btn.disabled=false}}
  function suggestRC(uc){let d=new Date(),date=d.getFullYear()+String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0");return "RC-"+date+"-"+uc.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,24)}
  window.openRoute=async id=>{let {data:r,error}=await sb.from("route_cards").select("*").eq("id",id).single();if(error){toast(error.message);return}activeRoute=r;let [rr]=await enrich([r]);tab("dashboard");show("routeDetail");$("routeDetail").innerHTML=`<h2>${esc(rr.part_number)} · ${esc(rr.po_number)} / ${esc(rr.po_line)}</h2><p><b>${esc(r.route_card_no)}</b> · UC ${esc(r.uc_batch)} · Heat ${esc(r.heat_batch||"—")} · Qty ${r.qty}</p><p>Current stage: ${esc(rr.stage_name||"—")} · Status: ${esc(r.status)} ${r.is_urgent?"🔴 URGENT":""}</p><div class="record-actions" id="routeActions"></div><div id="routeHistory"></div>`;
    let a=$("routeActions");if((ROLE_STAGE[profile.role]||[]).includes(stages.find(s=>s.id===r.current_stage_id)?.code)||profile.role==="admin")a.innerHTML+=`<button onclick="window.completeStage()">Complete Current Stage</button>`;
    a.innerHTML+=`<button class="secondary" onclick="window.releaseHandover()">Release Handover</button>`;
    if(["admin","supervisor"].includes(profile.role))a.innerHTML+=`<button class="secondary" onclick="window.toggleUrgent()">${r.is_urgent?"Remove Urgent":"Mark Urgent"}</button><button class="secondary" onclick="window.softDelete()">Remove Material</button>`;
    if(REWORK_ROLES.includes(profile.role))a.innerHTML+=`<button class="secondary" onclick="window.raiseRework()">Raise Rework</button>`;
    if(REJECT_ROLES.includes(profile.role))a.innerHTML+=`<button class="secondary" onclick="window.rejectMaterial()">Report Rejection</button>`;
    let {data:tx}=await sb.from("stage_transactions").select("*,process_stages(name),profiles(full_name)").eq("route_card_id",id).order("created_at",{ascending:false});$("routeHistory").innerHTML="<h3>Stage History</h3>"+(tx||[]).map(t=>`<div class="record"><b>${esc(t.process_stages?.name)}</b> · Qty ${t.quantity} · ${esc(t.status)}<p>${esc(t.profiles?.full_name||"")} · ${new Date(t.created_at).toLocaleString()}</p>${esc(t.remarks||"")}</div>`).join("");
  };
  window.completeStage=async()=>{let s=stages.find(s=>s.id===activeRoute.current_stage_id);let qty=prompt("Quantity completed:",activeRoute.qty);if(qty===null)return;let remarks=prompt("Remarks (optional):")||"";let {error}=await sb.from("stage_transactions").insert({route_card_id:activeRoute.id,stage_id:s.id,quantity:Number(qty),status:"completed",responsible_user_id:user.id,remarks});if(error)toast(error.message);else{toast("Stage completion recorded.");await openRoute(activeRoute.id);await dashboard()}};
  window.releaseHandover=async()=>{let options=stages.map(s=>`${s.sequence_order}. ${s.name}`).join("\n");let seq=prompt("Destination stage number:\n"+options);let dest=stages.find(s=>s.sequence_order===Number(seq));if(!dest)return;let qty=prompt("Quantity being handed over:",activeRoute.qty);if(qty===null)return;let carrier=prompt("Helper/carrier (optional):")||null;let remarks=prompt("Remarks (optional):")||null;let {error}=await sb.from("handovers").insert({route_card_id:activeRoute.id,quantity:Number(qty),from_stage_id:activeRoute.current_stage_id,to_stage_id:dest.id,released_by:user.id,helper_carrier:carrier,remarks});if(error)toast(error.message);else{toast("Handover released; awaiting receiver confirmation.");await openRoute(activeRoute.id);await dashboard()}};
  window.receiveHandover=async id=>{let qty=prompt("Quantity physically received:");if(qty===null)return;let remarks=prompt("Receipt remarks (optional):")||null;let {error}=await sb.from("receipts").insert({handover_id:id,received_by:user.id,quantity_received:Number(qty),remarks});if(error)toast(error.message);else{toast("Receipt confirmed.");await dashboard()}};
  window.toggleUrgent=async()=>{let urgent=!activeRoute.is_urgent,reason=urgent?(prompt("Urgent reason (optional):")||null):null;let {error}=await sb.from("route_cards").update({is_urgent:urgent,urgent_reason:reason,urgent_set_by:urgent?user.id:null,urgent_set_at:urgent?new Date().toISOString():null}).eq("id",activeRoute.id);if(error)toast(error.message);else{toast("Urgent flag updated.");await openRoute(activeRoute.id);await urgentListRefresh()}};
  async function urgent(){await urgentListRefresh()}async function urgentListRefresh(){let {data,error}=await sb.from("urgent_route_cards").select("*");if(error)toast(error.message);$("urgentList").innerHTML=(data||[]).map(r=>card({...r,is_urgent:true})).join("")||"<p>No urgent Route Cards.</p>"}
  window.softDelete=async()=>{if(!confirm("Soft-remove this Route Card? History will remain."))return;let {error}=await sb.from("route_cards").update({is_deleted:true,deleted_by:user.id,deleted_at:new Date().toISOString()}).eq("id",activeRoute.id);if(error)toast(error.message);else{show("routeDetail",false);toast("Route Card removed from active lists.");await dashboard()}};
  window.raiseRework=async()=>{let qty=prompt("Rework quantity:",activeRoute.qty);if(qty===null)return;let reason=prompt("Rework reason:");if(!reason)return;let {error}=await sb.from("rework_events").insert({route_card_id:activeRoute.id,stage_id:activeRoute.current_stage_id,quantity:Number(qty),reason,raised_by:user.id,status:"raised"});toast(error?error.message:"Rework raised.")};
  window.rejectMaterial=async()=>{let qty=prompt("Rejected quantity:");if(qty===null)return;let reason=prompt("Rejection reason:");if(!reason)return;let loc=prompt("Scrap location:");let {error}=await sb.from("rejection_events").insert({route_card_id:activeRoute.id,stage_id:activeRoute.current_stage_id,quantity:Number(qty),reason,reported_by:user.id,scrap_location:loc});toast(error?error.message:"Rejection reported.")};
  async function poDashboard(){let {data,error}=await sb.from("route_cards").select("*").eq("is_deleted",false);if(error){toast(error.message);return}let rows=await enrich(data||[]),counts={};rows.forEach(r=>{let k=r.stage_name||"Unassigned";counts[k]=(counts[k]||0)+Number(r.qty||0)});$("stageSummary").innerHTML="<h3>Plant-wide quantity by stage</h3><table><tr><th>Stage</th><th>Total quantity</th></tr>"+Object.entries(counts).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v}</td></tr>`).join("")+"</table>";let groups={};rows.forEach(r=>(groups[r.po_number+" / "+r.po_line]??=[]).push(r));$("poList").innerHTML=Object.entries(groups).map(([k,rs])=>`<details class="record"><summary><b>${esc(rs[0].part_number)}</b> · PO ${esc(k)} · ${rs.length} Route Cards</summary>${rs.map(r=>card(r)).join("")}</details>`).join("")}
  function parseQR(text){let out={};text.split("?").forEach(piece=>{let [k,...v]=piece.split("=");if(k&&v.length)out[decodeURIComponent(k).trim().toLowerCase().replace(/[^a-z0-9]/g,"")]=decodeURIComponent(v.join("=").replace(/\+/g," ")).trim()});const pick=(...keys)=>{for(let k of keys)if(out[k])return out[k];return""};return {part:pick("partnumber","partno","part"),po:pick("ponumber","pono","po"),line:pick("poline","polineno","line"),poqty:pick("poqty","poquantity"),heat:pick("heatno","heatbatch","heat"),uc:pick("ucbatch","ucbatchno","uc"),qty:pick("batchqty","qty","quantity"),raw:text}}
  async function startScan(target){scanTarget=target;show("scanBox");try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});$("camera").srcObject=stream;await $("camera").play();scanLoop()}catch(e){toast("Camera unavailable: "+e.message)}}
  function scanLoop(){if(!stream)return;let v=$("camera"),c=$("qrCanvas"),ctx=c.getContext("2d");if(v.readyState===v.HAVE_ENOUGH_DATA){c.width=v.videoWidth;c.height=v.videoHeight;ctx.drawImage(v,0,0,c.width,c.height);let code=null;if("BarcodeDetector"in window){/* jsQR fallback below remains active */}let img=ctx.getImageData(0,0,c.width,c.height);code=window.jsQR?.(img.data,img.width,img.height,{inversionAttempts:"attemptBoth"});if(code){let parsed=parseQR(code.data);stopScan();if(scanTarget==="new"){ $("partNumber").value=parsed.part;$("poNumber").value=parsed.po;$("poLine").value=parsed.line;$("poQty").value=parsed.poqty;$("heatBatch").value=parsed.heat;$("ucBatch").value=parsed.uc;$("routeQty").value=parsed.qty;$("routeCardNo").value=suggestRC(parsed.uc);$("qrPayload").value=parsed.raw;tab("new")}else{$("searchInput").value=parsed.uc||parsed.raw;search()}return}}requestAnimationFrame(scanLoop)}
  function stopScan(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}show("scanBox",false)}
  init();
})();
if ("serviceWorker" in navigator && location.protocol.startsWith("http")) navigator.serviceWorker.register("./sw.js").catch(()=>{});
